### ISSUE TITLE
[Bug] "got an unexpected keyword argument 'encoding'" from json.loads deserialization 

### ISSUE THREAD

**Issue by Rprloekwirt** [sinkaroid/booru#2]
**Describe the bug**
When running the gelbooru example: 
```
gel = booru.Gelbooru()
res = await gel.search(query="cat_girl", limit=50)
```
I get an error:

> parser.py", line 145, in deserialize
>     return json.loads(better_object(data), encoding="utf-8")
>   File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
>     return cls(**kw).decode(s)
> TypeError: __init__() got an unexpected keyword argument 'encoding'

**To Reproduce**
Run the gelbooru example from the pip install page.

**Expected behavior**
Retrieves an image from gelbooru. 

**Desktop (please complete the following information):**
 - OS: Debian
 - Python version: 3.9

**Comment by sinkaroid** [comment]
Yes actually you right, the argument `encoding` was removed from [json.loads](https://docs.python.org/3/library/json.html#json.loads) in `Python 3.9`  
I will fix and make optional method soon

**Comment by sinkaroid** [comment]
Please check new release, that was fixed
