### ISSUE TITLE
String slices must be integers.

### ISSUE THREAD

**Issue by heav33n** [sinkaroid/booru#9]
**Describe the bug**
try:
    images = [i["file_url"] for i in data]

except:
    images = [i["file"]["url"] for i in data]

Gives the error. This is yours interpreter.

**To Reproduce**
1. Use parse_image(result) on:
result = await r34.search_image("neko", limit=2) # test

**Expected behavior**
Give me only the url.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Python version: 3.10.10 and 3.11.3

**Additional context**
No.

**Comment by sinkaroid** [comment]
I tested on 3.10.11 everything works fine until some of my testing network marked as spam thus captcha were found on r34,
but it should throwing some `JSONDecodeError` instead `String slices must be integers`
![Screenshot_574](https://user-images.githubusercontent.com/12372481/232340756-6a5677ba-2645-4e68-b0ea-2f6b4e59d40d.png)

Could you tell some moreinfo pls

**Comment by heav33n** [comment]
hi, i have good news, i just discover that this:
```python
async def main():
    r34 = Rule34()
    img = await r34.search(query="sexy", limit=1)
    img = json.loads(img)
    urls = [item['file_url'] for item in img if item['file_url'].startswith('https://api-cdn.rule34.xxx/images/')]
    print(urls)

asyncio.run(main())
```
parses the images correctly :D

**Comment by rV4nxZ** [comment]
I am trying to implement it in the parse_image function

**Comment by rV4nxZ** [comment]
wait why now it is not working

**Comment by heav33n** [comment]
it only works without the "gacha" tag, works with the "limit" tag

**Comment by sinkaroid** [comment]
When using gacha method, all returns only 1 object/dict, so your loop statements is no use then

**Comment by heav33n** [comment]
fixed it
```python
    img = await r34.search(query="sexy", gacha=True)

    if isinstance(img, str):
        # if img is a string, parse it as JSON
        data = json.loads(img)
        urls = [data['file_url']] if data['file_url'].startswith('https://api-cdn.') else []
    else:
        # if img is a list of image objects, extract the file urls
        data = json.loads(img)
        urls = [item['file_url'] for item in data if item['file_url'].startswith('https://api-cdn.')]

    print(urls)
```
now i'll try to add it to the parse_image function and use the resolve instead of data = json.loads(img) to follow your code

**Comment by heav33n** [comment]
updated function:

```python
def parse_image_r34(raw_object: dict):
    if isinstance(raw_object, str):
        data = json.loads(raw_object)
        urls = [data['file_url']] if data['file_url'].startswith('https://api-cdn.') else []
    else:
        data = json.loads(raw_object)
        urls = [item['file_url'] for item in data if item['file_url'].startswith('https://api-cdn.')]
```
output:
['https://api-cdn.rule34.xxx/images/6747/48766c19aac641cae347e3a4180e817a.png']

**Comment by sinkaroid** [comment]
You can always submit PR if the current flow is a bit clunky on your side

**Comment by sinkaroid** [comment]
> fixed it
> 
> ```python
>     img = await r34.search(query="sexy", gacha=True)
> 
>     if isinstance(img, str):
>         # if img is a string, parse it as JSON
>         data = json.loads(img)
>         urls = [data['file_url']] if data['file_url'].startswith('https://api-cdn.') else []
>     else:
>         # if img is a list of image objects, extract the file urls
>         data = json.loads(img)
>         urls = [item['file_url'] for item in data if item['file_url'].startswith('https://api-cdn.')]
> 
>     print(urls)
> ```
> 
> now i'll try to add it to the parse_image function and use the resolve instead of data = json.loads(img) to follow your code

What is the point reinventing urls with loop, while img is only single object, there is still make sense if you re-validating them in normal search not gacha

**Comment by heav33n** [comment]
well for me it works for what i need
